# PortSentry Configuration

#######################
# Port Configurations #
#######################
# Use these if you just want to be aware:
TCP_PORTS="1,11,15,79,111,119,143,540,635,1524,2000,5742,6667,12345,12346,20034,27665,31337,32771,32772,32773,32774,40421,49724,54320"
UDP_PORTS="1,7,69,161,162,513,635,640,641,700,37444,34555,31335,32770,32771,32772,32773,32774,31337,54321"

###########################################
# Advanced Stealth Scan Detection Options #
###########################################
ADVANCED_PORTS_TCP="113,139,179,1024"
ADVANCED_PORTS_UDP="67,137,138,520,1024"

# Default TCP ident and NetBIOS service
ADVANCED_EXCLUDE_TCP="113,139"
# Default UDP route (RIP), NetBIOS, bootp broadcasts.
ADVANCED_EXCLUDE_UDP="520,138,137,67"

######################
# Configuration Files#
######################
# Hosts to ignore
IGNORE_FILE="/var/portsentry.ignore"
# Hosts that have been denied (running history)
HISTORY_FILE="/var/portsentry.history"
# Hosts that have been denied this session only (temporary until next restart)
BLOCKED_FILE="/var/portsentry.blocked"

##############################
# Misc. Configuration Options#
##############################
RESOLVE_HOST = "1"

##################
# Ignore Options #
##################
# 0 = Do not block UDP/TCP scans.
# 1 = Block UDP/TCP scans.
# 2 = Run external command only (KILL_RUN_CMD)

BLOCK_UDP="1"
BLOCK_TCP="1"

###################
# Dropping Routes:#
###################
# iptables support for Linux
KILL_ROUTE="/bin/iptables -I INPUT -s $TARGET$ -j DROP"

###############
# TCP Wrappers#
###############
KILL_HOSTS_DENY="ALL: $TARGET$"

#####################
# Scan trigger value#
#####################
SCAN_TRIGGER="2"

