#!/bin/sh

case "${ACTION}" in
 add)
  mcr-usbmount $1
  ;;
  *)
   mcr-usbmount $1
   ;;
esac

PID_FILE=/var/run/usbStorageD_pid
if [ -e $PID_FILE ]; then
	echo 0 > /proc/zq_mcr_secure_policy
        PID=`cat $PID_FILE`
        kill -USR1 $PID
	echo 1 > /proc/zq_mcr_secure_policy
fi      
