#!/bin/sh

touch /etc/config/setup
touch /etc/config/wireless

board_name="$(ubus call system board 2>/dev/null | jsonfilter -e '@.board_name' 2>/dev/null)"
default_setup_ipaddr="192.168.1.20"
default_setup_netmask="255.255.255.0"
default_wifi_ssid="ALemprator-KT-KM12-007H"
other_wifi_ssid="ALemprator-KT-KM14-102H"

case "$board_name" in
	kt,km14-102h)
		default_wifi_ssid="ALemprator-KT-KM14-102H"
		other_wifi_ssid="ALemprator-KT-KM12-007H"
		;;
	kt,km15-103h)
		default_wifi_ssid="ALemprator-KT-KM15-103H"
		other_wifi_ssid="ALemprator-KT-KM12-007H"
		;;
	kt,dv02-012h)
		default_wifi_ssid="ALemprator-KT-DV02-012H"
		other_wifi_ssid="ALemprator-KT-AR07-102H"
		;;
	kt,ar07-102h)
		default_wifi_ssid="ALemprator-KT-AR07-102H"
		other_wifi_ssid="ALemprator-KT-DV02-012H"
		;;
	kt,ar06-012h)
		default_wifi_ssid="ALemprator-KT-AR06-012H"
		other_wifi_ssid="ALemprator-KT-AR07-102H"
		;;
	lg,gapd-7500)
		default_wifi_ssid="ALemprator-KT-LG-GAPD-7500"
		other_wifi_ssid="ALemprator-KT-DV02-012H"
		;;
	kt,km12-007h|'')
		;;
esac

lan_ipaddr="$(uci -q get network.lan.ipaddr)"
lan_netmask="$(uci -q get network.lan.netmask)"
wifi_ssid="$(uci -q get wireless.@wifi-iface[0].ssid)"
wifi_key="$(uci -q get wireless.@wifi-iface[0].key)"

[ -n "$lan_ipaddr" ] || lan_ipaddr="$default_setup_ipaddr"
[ -n "$lan_netmask" ] || lan_netmask="255.255.255.0"
[ -n "$wifi_ssid" ] || wifi_ssid="$default_wifi_ssid"
[ "$wifi_ssid" = "OpenWrt" ] && wifi_ssid="$default_wifi_ssid"
[ "$wifi_ssid" = "$other_wifi_ssid" ] && wifi_ssid="$default_wifi_ssid"

has_setup_default=0
uci -q get setup.default >/dev/null && has_setup_default=1

if [ "$has_setup_default" = 1 ]; then
	existing_lan_ipaddr="$(uci -q get setup.default.lan_ipaddr)"
	existing_wifi_ssid="$(uci -q get setup.default.wifi_ssid)"
	existing_initial_setup_complete="$(uci -q get setup.default.initial_setup_complete)"
	case "$existing_lan_ipaddr" in
		''|192.168.1.1|192.168.1.21|192.168.1.22) uci -q set setup.default.lan_ipaddr="$default_setup_ipaddr" ;;
	esac
	uci -q get setup.default.lan_netmask >/dev/null || uci -q set setup.default.lan_netmask="$default_setup_netmask"
	case "$existing_wifi_ssid" in
		''|OpenWrt|Alemprator|ALemprator|"$other_wifi_ssid") uci -q set setup.default.wifi_ssid="$wifi_ssid" ;;
	esac
	uci -q get setup.default.AlwSettings >/dev/null || uci -q set setup.default.AlwSettings='AL'
	uci -q get setup.default.wifi_ssid_5g_mode >/dev/null || uci -q set setup.default.wifi_ssid_5g_mode='derived'
	uci -q get setup.default.wifi_ssid_5g >/dev/null || uci -q set setup.default.wifi_ssid_5g=''
	uci -q get setup.default.wifi_ssid_vlan >/dev/null || uci -q set setup.default.wifi_ssid_vlan=''
	if ! uci -q get setup.default.wifi_ssid_vlan_2g >/dev/null; then
		existing_vlan_ssid="$(uci -q get setup.default.wifi_ssid_vlan)"
		uci -q set setup.default.wifi_ssid_vlan_2g="$existing_vlan_ssid"
	fi
	uci -q get setup.default.wifi_ssid_vlan_5g >/dev/null || uci -q set setup.default.wifi_ssid_vlan_5g=''
	uci -q get setup.default.channel_2g >/dev/null || uci -q set setup.default.channel_2g='auto'
	uci -q get setup.default.channel_5g >/dev/null || uci -q set setup.default.channel_5g='auto'
	uci -q get setup.default.wifi_mode_2g >/dev/null || uci -q set setup.default.wifi_mode_2g='ax'
	uci -q get setup.default.wifi_width_2g >/dev/null || uci -q set setup.default.wifi_width_2g='20'
	uci -q get setup.default.wifi_mode_5g >/dev/null || uci -q set setup.default.wifi_mode_5g='ax'
	uci -q get setup.default.wifi_width_5g >/dev/null || uci -q set setup.default.wifi_width_5g='80'
	uci -q get setup.default.reset_button_disabled >/dev/null || uci -q set setup.default.reset_button_disabled='0'
	uci -q get setup.default.reset_hold_seconds >/dev/null || uci -q set setup.default.reset_hold_seconds='5'
	uci -q get setup.default.wps_button_disabled >/dev/null || uci -q set setup.default.wps_button_disabled='0'
	case "$existing_initial_setup_complete" in
		'') uci -q set setup.default.initial_setup_complete='0' ;;
	esac
	uci -q get setup.default.hotspot_quick_enabled >/dev/null || uci -q set setup.default.hotspot_quick_enabled='0'
	uci -q get setup.default.hotspot_quick_wan_interface >/dev/null || uci -q set setup.default.hotspot_quick_wan_interface='wan'
	uci -q get setup.default.hotspot_quick_subscriber_interface >/dev/null || uci -q set setup.default.hotspot_quick_subscriber_interface='hotspot'
	uci -q get setup.default.hotspot_quick_subscriber_interface_2 >/dev/null || uci -q set setup.default.hotspot_quick_subscriber_interface_2='hotspot2'
	uci -q get setup.default.hotspot_quick_ssid_1 >/dev/null || uci -q set setup.default.hotspot_quick_ssid_1='Hotspot-1'
	uci -q get setup.default.hotspot_quick_gateway_1 >/dev/null || uci -q set setup.default.hotspot_quick_gateway_1='192.168.10.1'
	uci -q get setup.default.hotspot_quick_pool_start_1 >/dev/null || uci -q set setup.default.hotspot_quick_pool_start_1='192.168.10.10'
	uci -q get setup.default.hotspot_quick_pool_end_1 >/dev/null || uci -q set setup.default.hotspot_quick_pool_end_1='192.168.10.199'
	uci -q get setup.default.hotspot_quick_policy_1 >/dev/null || uci -q set setup.default.hotspot_quick_policy_1='standard'
	uci -q get setup.default.hotspot_quick_secondary_enabled >/dev/null || uci -q set setup.default.hotspot_quick_secondary_enabled='0'
	uci -q get setup.default.hotspot_quick_ssid_2 >/dev/null || uci -q set setup.default.hotspot_quick_ssid_2='Hotspot-2'
	uci -q get setup.default.hotspot_quick_gateway_2 >/dev/null || uci -q set setup.default.hotspot_quick_gateway_2='192.168.20.1'
	uci -q get setup.default.hotspot_quick_pool_start_2 >/dev/null || uci -q set setup.default.hotspot_quick_pool_start_2='192.168.20.10'
	uci -q get setup.default.hotspot_quick_pool_end_2 >/dev/null || uci -q set setup.default.hotspot_quick_pool_end_2='192.168.20.199'
	uci -q get setup.default.hotspot_quick_policy_2 >/dev/null || uci -q set setup.default.hotspot_quick_policy_2='premium'
	uci -q get setup.default.hotspot_quick_radius_server >/dev/null || uci -q set setup.default.hotspot_quick_radius_server='192.168.1.2'
	uci -q get setup.default.hotspot_quick_radius_server2 >/dev/null || uci -q set setup.default.hotspot_quick_radius_server2=''
	uci -q get setup.default.hotspot_quick_radius_secret >/dev/null || uci -q set setup.default.hotspot_quick_radius_secret=''
	uci -q get setup.default.hotspot_quick_radius_auth_port >/dev/null || uci -q set setup.default.hotspot_quick_radius_auth_port='1812'
	uci -q get setup.default.hotspot_quick_radius_acct_port >/dev/null || uci -q set setup.default.hotspot_quick_radius_acct_port='1813'
	uci -q get setup.default.hotspot_quick_radius_nas_ip >/dev/null || uci -q set setup.default.hotspot_quick_radius_nas_ip=''
	uci -q get setup.default.hotspot_quick_nas_id >/dev/null || uci -q set setup.default.hotspot_quick_nas_id=''
	uci -q get setup.default.hotspot_quick_acct_interim >/dev/null || uci -q set setup.default.hotspot_quick_acct_interim='60'
	uci -q get setup.default.hotspot_quick_coa_enabled >/dev/null || uci -q set setup.default.hotspot_quick_coa_enabled='0'
	uci -q get setup.default.hotspot_quick_coa_port >/dev/null || uci -q set setup.default.hotspot_quick_coa_port='3799'
	uci -q get setup.default.hotspot_quick_trial_enabled >/dev/null || uci -q set setup.default.hotspot_quick_trial_enabled='0'
	uci -q get setup.default.hotspot_quick_trial_duration >/dev/null || uci -q set setup.default.hotspot_quick_trial_duration='30'
	uci -q get setup.default.hotspot_quick_trial_uptime_limit >/dev/null || uci -q set setup.default.hotspot_quick_trial_uptime_limit='30'
	uci -q get setup.default.hotspot_quick_mac_auth_enabled >/dev/null || uci -q set setup.default.hotspot_quick_mac_auth_enabled='0'
	uci -q get setup.default.hotspot_quick_mac_auth_suffix >/dev/null || uci -q set setup.default.hotspot_quick_mac_auth_suffix='@mac'
	uci -q get setup.default.hotspot_quick_mac_auth_password >/dev/null || uci -q set setup.default.hotspot_quick_mac_auth_password=''
	uci -q get setup.default.hotspot_quick_walled_garden >/dev/null || uci -q set setup.default.hotspot_quick_walled_garden=''
	uci -q get setup.default.hotspot_quick_domain >/dev/null || uci -q set setup.default.hotspot_quick_domain='hotspot.local'
	uci -q get setup.default.hotspot_quick_dns1 >/dev/null || uci -q set setup.default.hotspot_quick_dns1='8.8.8.8'
	uci -q get setup.default.hotspot_quick_dns2 >/dev/null || uci -q set setup.default.hotspot_quick_dns2='82.114.163.31'
	uci -q get setup.default.hotspot_quick_login_mode >/dev/null || uci -q set setup.default.hotspot_quick_login_mode='both'
	uci -q get setup.default.hotspot_quick_rate_limit >/dev/null || uci -q set setup.default.hotspot_quick_rate_limit='2M/5M'
	uci -q get setup.default.hotspot_quick_mac_cookie_enabled >/dev/null || uci -q set setup.default.hotspot_quick_mac_cookie_enabled='0'
	uci -q get setup.default.hotspot_quick_available_speeds >/dev/null || uci -q set setup.default.hotspot_quick_available_speeds='1M/2M Standard\n2M/4M Fast'
	uci -q get setup.default.hotspot_quick_support_phone >/dev/null || uci -q set setup.default.hotspot_quick_support_phone=''
	uci -q get setup.default.hotspot_quick_notice_text >/dev/null || uci -q set setup.default.hotspot_quick_notice_text='أهلاً بكم في شبكتنا'
	uci -q get setup.default.hotspot_quick_speedtest_enabled >/dev/null || uci -q set setup.default.hotspot_quick_speedtest_enabled='0'
	uci -q get setup.default.hotspot_quick_browser_cookie_enabled >/dev/null || uci -q set setup.default.hotspot_quick_browser_cookie_enabled='1'
	uci -q get setup.default.hotspot_quick_browser_cookie_days >/dev/null || uci -q set setup.default.hotspot_quick_browser_cookie_days='7'
	uci -q get setup.default.hotspot_quick_userman_rest_enabled >/dev/null || uci -q set setup.default.hotspot_quick_userman_rest_enabled='0'
	uci -q get setup.default.hotspot_quick_userman_rest_scheme >/dev/null || uci -q set setup.default.hotspot_quick_userman_rest_scheme='https'
	uci -q get setup.default.hotspot_quick_userman_rest_username >/dev/null || uci -q set setup.default.hotspot_quick_userman_rest_username='hotspot-read'
	uci -q get setup.default.hotspot_quick_userman_rest_password >/dev/null || uci -q set setup.default.hotspot_quick_userman_rest_password=''
	uci -q commit setup
	rm -f /tmp/luci-indexcache
	exit 0
fi

uci -q batch <<EOF >/dev/null
	set setup.default=setup
	set setup.default.AlwSettings='AL'
	set setup.default.lan_ipaddr='$default_setup_ipaddr'
	set setup.default.lan_netmask='$default_setup_netmask'
	set setup.default.mode='ap'
	set setup.default.wifi_ssid='$wifi_ssid'
	set setup.default.wifi_ssid_5g_mode='derived'
	set setup.default.wifi_ssid_5g=''
	set setup.default.wifi_ssid_vlan=''
	set setup.default.wifi_ssid_vlan_2g=''
	set setup.default.wifi_ssid_vlan_5g=''
	set setup.default.wifi_key='$wifi_key'
	set setup.default.uplink_ssid=''
	set setup.default.uplink_key=''
	set setup.default.uplink_band='2g'
	set setup.default.mesh_id=''
	set setup.default.mesh_key=''
	set setup.default.mesh_band='2g'
	set setup.default.is_vlan='0'
	set setup.default.vlan_id='10'
	set setup.default.channel_2g='auto'
	set setup.default.channel_5g='auto'
	set setup.default.wifi_mode_2g='ax'
	set setup.default.wifi_width_2g='20'
	set setup.default.wifi_mode_5g='ax'
	set setup.default.wifi_width_5g='80'
	set setup.default.reset_button_disabled='0'
	set setup.default.reset_hold_seconds='5'
	set setup.default.wps_button_disabled='0'
	set setup.default.initial_setup_complete='0'
	set setup.default.hotspot_quick_enabled='0'
	set setup.default.hotspot_quick_wan_interface='wan'
	set setup.default.hotspot_quick_subscriber_interface='hotspot'
	set setup.default.hotspot_quick_subscriber_interface_2='hotspot2'
	set setup.default.hotspot_quick_ssid_1='Hotspot-1'
	set setup.default.hotspot_quick_gateway_1='192.168.10.1'
	set setup.default.hotspot_quick_pool_start_1='192.168.10.10'
	set setup.default.hotspot_quick_pool_end_1='192.168.10.199'
	set setup.default.hotspot_quick_policy_1='standard'
	set setup.default.hotspot_quick_secondary_enabled='0'
	set setup.default.hotspot_quick_ssid_2='Hotspot-2'
	set setup.default.hotspot_quick_gateway_2='192.168.20.1'
	set setup.default.hotspot_quick_pool_start_2='192.168.20.10'
	set setup.default.hotspot_quick_pool_end_2='192.168.20.199'
	set setup.default.hotspot_quick_policy_2='premium'
	set setup.default.hotspot_quick_radius_server='192.168.1.2'
	set setup.default.hotspot_quick_radius_server2=''
	set setup.default.hotspot_quick_radius_secret=''
	set setup.default.hotspot_quick_radius_auth_port='1812'
	set setup.default.hotspot_quick_radius_acct_port='1813'
	set setup.default.hotspot_quick_radius_nas_ip=''
	set setup.default.hotspot_quick_nas_id=''
	set setup.default.hotspot_quick_acct_interim='60'
	set setup.default.hotspot_quick_coa_enabled='0'
	set setup.default.hotspot_quick_coa_port='3799'
	set setup.default.hotspot_quick_trial_enabled='0'
	set setup.default.hotspot_quick_trial_duration='30'
	set setup.default.hotspot_quick_trial_uptime_limit='30'
	set setup.default.hotspot_quick_mac_auth_enabled='0'
	set setup.default.hotspot_quick_mac_auth_suffix='@mac'
	set setup.default.hotspot_quick_mac_auth_password=''
	set setup.default.hotspot_quick_walled_garden=''
	set setup.default.hotspot_quick_domain='hotspot.local'
	set setup.default.hotspot_quick_dns1='8.8.8.8'
	set setup.default.hotspot_quick_dns2='82.114.163.31'
	set setup.default.hotspot_quick_login_mode='both'
	set setup.default.hotspot_quick_rate_limit='2M/5M'
	set setup.default.hotspot_quick_mac_cookie_enabled='0'
	set setup.default.hotspot_quick_available_speeds='1M/2M Standard\n2M/4M Fast'
	set setup.default.hotspot_quick_support_phone=''
	set setup.default.hotspot_quick_notice_text='أهلاً بكم في شبكتنا'
	set setup.default.hotspot_quick_speedtest_enabled='0'
	set setup.default.hotspot_quick_browser_cookie_enabled='1'
	set setup.default.hotspot_quick_browser_cookie_days='7'
	set setup.default.hotspot_quick_userman_rest_enabled='0'
	set setup.default.hotspot_quick_userman_rest_scheme='https'
	set setup.default.hotspot_quick_userman_rest_username='hotspot-read'
	set setup.default.hotspot_quick_userman_rest_password=''
	commit setup
EOF

rm -f /tmp/luci-indexcache
exit 0
