#!/bin/sh /etc/rc.common
# Copyright (C) 2023-2026 muink
#

. "${IPKG_INSTROOT}/lib/functions.sh"
. "${IPKG_INSTROOT}/usr/share/libubox/jshn.sh"

START=99
USE_PROCD=1

# uci
CONFIG_NAME='netspeedtest'
NAMEDDSECTION='config'
LIBRESPEED_CONFIG_NAME='librespeed-go'
LIBRESPEED_INSTANCE='librespeed-go'
LIBRESPEED_PROG='/usr/bin/librespeed-go'
LIBRESPEED_TMPCONF='/var/run/librespeed-go/settings.json'
OPENSPEEDTEST_INSTANCE='openspeedtest'
OPENSPEEDTEST_PROG='/usr/sbin/uhttpd'
OPENSPEEDTEST_SHARE='/usr/share/netspeedtest/openspeedtest'
OPENSPEEDTEST_RUN='/var/run/netspeedtest/openspeedtest'
OPENSPEEDTEST_DOWNLOAD_SIZE_MB='32'



iperf3_instance() {
	procd_open_instance "iperf3"
	procd_set_param command "iperf3"
	procd_append_param command -s
	procd_set_param respawn
	procd_set_param user nobody
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

librespeed_instance() {
	local action="$1"

	case "$action" in
		start)
			[ -x "$LIBRESPEED_PROG" ] || return 1

			uci set $LIBRESPEED_CONFIG_NAME.config.enabled='0'
			uci commit $LIBRESPEED_CONFIG_NAME

			mkdir -p "${LIBRESPEED_TMPCONF%/*}"

			json_init
			option_cb() {
				local name="$1"
				local value="$2"

				case "$name" in
					enabled) ;;
					enable_tls|enable_http2|redact_ip_addresses)
						json_add_boolean "$name" "$value"
						;;
					*)
						json_add_string "$name" "$value"
						;;
				esac
			}
			config_load "$LIBRESPEED_CONFIG_NAME"
			json_dump > "$LIBRESPEED_TMPCONF"
			chown librespeed "$LIBRESPEED_TMPCONF"

			procd_open_instance "$LIBRESPEED_INSTANCE"
			procd_set_param command "$LIBRESPEED_PROG"
			procd_append_param command -c "$LIBRESPEED_TMPCONF"
			procd_set_param respawn
			procd_set_param user librespeed
			procd_set_param stdout 1
			procd_set_param stderr 1
			procd_close_instance
		;;
		stop)
			uci set $LIBRESPEED_CONFIG_NAME.config.enabled='0'
			uci commit $LIBRESPEED_CONFIG_NAME
			rm -rf "${LIBRESPEED_TMPCONF%/*}"
		;;
	esac
}

openspeedtest_instance() {
	local action="$1"
	local port

	case "$action" in
		start)
			[ -x "$OPENSPEEDTEST_PROG" ] || return 1
			[ -f "$OPENSPEEDTEST_SHARE/index.html" ] || return 1

			config_get port "$NAMEDDSECTION" openspeedtest_server_port '3000'
			case "$port" in
				''|*[!0-9]*) port='3000' ;;
			esac

			rm -rf "$OPENSPEEDTEST_RUN"
			mkdir -p "$OPENSPEEDTEST_RUN"
			ln -s "$OPENSPEEDTEST_SHARE/assets" "$OPENSPEEDTEST_RUN/assets"
			ln -s "$OPENSPEEDTEST_SHARE/cgi-bin" "$OPENSPEEDTEST_RUN/cgi-bin"
			ln -s "$OPENSPEEDTEST_SHARE/index.html" "$OPENSPEEDTEST_RUN/index.html"
			ln -s "$OPENSPEEDTEST_SHARE/License.md" "$OPENSPEEDTEST_RUN/License.md"
			dd if=/dev/zero of="$OPENSPEEDTEST_RUN/downloading" bs=1048576 count=0 seek="$OPENSPEEDTEST_DOWNLOAD_SIZE_MB" 2>/dev/null

			procd_open_instance "$OPENSPEEDTEST_INSTANCE"
			procd_set_param command "$OPENSPEEDTEST_PROG"
			procd_append_param command -f
			procd_append_param command -h "$OPENSPEEDTEST_RUN"
			procd_append_param command -r 'OpenSpeedTest'
			procd_append_param command -I index.html
			procd_append_param command -x /cgi-bin
			procd_append_param command -y /upload=/cgi-bin
			procd_append_param command -D
			procd_append_param command -t 65
			procd_append_param command -T 65
			procd_append_param command -N 128
			procd_append_param command -p "0.0.0.0:$port"
			procd_set_param respawn
			procd_set_param stdout 1
			procd_set_param stderr 1
			procd_close_instance
		;;
		stop)
			rm -rf "$OPENSPEEDTEST_RUN"
		;;
	esac
}

kill_instance() {
	local instance="$1"
	pgrep -f "$instance" | xargs kill -9 >/dev/null 2>&1
	return 0
}

start_service() {
	local eniperf3 enlibrespeed enopenspeedtest

	config_load "$CONFIG_NAME"
	eval "eniperf3=\$CONFIG_${NAMEDDSECTION}_iperf3_enabled"
	eval "enlibrespeed=\$CONFIG_${NAMEDDSECTION}_librespeed_enabled"
	eval "enopenspeedtest=\$CONFIG_${NAMEDDSECTION}_openspeedtest_server_enabled"

	[ "$eniperf3" == "1" ] && iperf3_instance
	[ "${enlibrespeed:=0}" == "0" ] && librespeed_instance stop || librespeed_instance start
	[ "${enopenspeedtest:=0}" == "0" ] && openspeedtest_instance stop || openspeedtest_instance start
}

service_triggers() {
	procd_add_reload_trigger "$CONFIG_NAME" 'librespeed-go' 'network'
}

stop_service() {
	uci -q batch <<-EOF
		set $CONFIG_NAME.$NAMEDDSECTION.iperf3_enabled='0'
		set $CONFIG_NAME.$NAMEDDSECTION.librespeed_enabled='0'
		set $CONFIG_NAME.$NAMEDDSECTION.openspeedtest_server_enabled='0'
		commit $CONFIG_NAME
	EOF
	librespeed_instance stop
	openspeedtest_instance stop
}

restart() {
	kill_instance "iperf3"
	kill_instance "$OPENSPEEDTEST_RUN"
	librespeed_instance stop
	openspeedtest_instance stop
	start
}
