#!/bin/sh /etc/rc.common

START=94
STOP=15
USE_PROCD=1

start_service() {
	# Only start if hotspot is enabled
	local enabled
	enabled="$(uci -q get hotspot_openwrt.main.enabled)"
	[ "$enabled" = "1" ] || return 0

	procd_open_instance "radius-proxy"
	procd_set_param command /usr/bin/lua /usr/libexec/hotspot-openwrt/radius-proxy
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}
